# Generated by Django 5.1.1 on 2025-11-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название приложения')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('user', 'Активный пользователь'), ('manager', 'Менеджер'), ('admin', 'Администратор')], max_length=7, verbose_name='Роль')),
                ('get_list_permission', models.BooleanField(default=False, verbose_name='Получение списка объектов')),
                ('create_obj_permission', models.BooleanField(default=False, verbose_name='Создание объекта')),
                ('get_obj_permission', models.BooleanField(default=False, verbose_name='Получение объекта')),
                ('update_obj_permission', models.BooleanField(default=False, verbose_name='Обновление объекта')),
                ('partial_update_obj_permission', models.BooleanField(default=False, verbose_name='Частичное обновление объекта')),
                ('delete_obj_permission', models.BooleanField(default=False, verbose_name='Удаление объекта')),
                ('owner_permission', models.BooleanField(default=False, verbose_name='Имеет ли автор отдельный доступ к созданному объекту')),
                ('business_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_app', to='permissions.businesselements', verbose_name='приложение')),
            ],
            options={
                'verbose_name': 'Разрешения',
                'verbose_name_plural': 'Разрешения',
                'ordering': ('business_element__slug',),
                'constraints': [models.UniqueConstraint(fields=('business_element', 'role'), name='Права для приложения с такой ролью пользователя уже заданы.')],
            },
        ),
    ]
